### ISSUE TITLE
Cancellations could not be saved"hide videos shorter than 20 minutes"

### ISSUE THREAD

**Issue by oonice** [porjo/freshtube#1]
I don't want to hide any videos, so I want to uncheck it. But refreshing the page will only return the same
I want to know how channel is sorted,  Is it the order of adding?, Whether live streams and new videos can be prioritized

**Comment by porjo** [comment]
Thanks for your interest - first issue! :smile:

I tried ticking the box and refreshing, then unticking the box and refreshing - worked fine for me. Can you provide your web browser and version?

> I want to know how channel is sorted, Is it the order of adding?

Channels are displayed in the order that the response from Youtube API is returned (effectively random).

> Whether live streams and new videos can be prioritized

I'm not sure what you mean. Can you provide an example of how you'd like the display to change for a prioritised video?
